# Copyright Contributors to the Open Cluster Management project

fullnameOverride: null
nameOverride: null

org: open-cluster-management
replicas: 1
args:
  frequency: 30
  logLevel: 0
  pkgLogLevel: -1
  logEncoding: console
securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
hubKubeConfigSecret: iam-policy-controller-hub-kubeconfig

resources:
  requests:
    memory: "150Mi"
  limits:
    memory: "300Mi"

affinity: {}

tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists
- effect: NoSchedule
  key: node.kubernetes.io/not-ready
  operator: Exists
- key: node-role.kubernetes.io/infra
  operator: Exists
  effect: NoSchedule

clusterName: null

global:
  imagePullPolicy: IfNotPresent
  imagePullSecret: open-cluster-management-image-pull-credentials
  imageOverrides:
    iam_policy_controller: quay.io/stolostron/iam-policy-controller:latest
  nodeSelector: {}
  proxyConfig:
    HTTP_PROXY: null
    HTTPS_PROXY: null
    NO_PROXY: null
