# Copyright Contributors to the Open Cluster Management project

fullnameOverride: null
nameOverride: null

org: open-cluster-management
replicas: 1
args:
  frequency: 30
  defaultDuration: null
  logLevel: 0
  pkgLogLevel: -1
  logEncoder: console
hubKubeConfigSecret: cert-policy-controller-hub-kubeconfig

affinity: {}

tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/not-ready
    operator: Exists
  - key: node-role.kubernetes.io/infra
    operator: Exists
    effect: NoSchedule

clusterName: null
managedKubeConfigSecret: null

# This is the Kubernetes distribution of the managed cluster. If set to OpenShift,
# some features such as automatic TLS certificate generation will be used.
# kubernetesDistribution: OpenShift
# hostingKubernetesDistribution: OpenShift

# This will expose metrics over HTTP if it's not an OpenShift cluster.
prometheus:
  # This will be automatically enabled if it's an OpenShift cluster.
  enabled: false
  serviceMonitor:
    # This will be automatically set to the controller's namespace.
    namespace: null

global:
  resourceRequirements:
    - containerIDRegex: ^.+:.+:.+$
      resources:
        requests:
          memory: "150Mi"
        limits:
          memory: "300Mi"
  imagePullPolicy: IfNotPresent
  imagePullSecret: open-cluster-management-image-pull-credentials
  imageOverrides:
    cert_policy_controller: quay.io/stolostron/cert-policy-controller:latest
  nodeSelector: {}
  proxyConfig:
    HTTP_PROXY: null
    HTTPS_PROXY: null
    NO_PROXY: null
