# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controller.fullname" . }}-info
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "controller.fullname" . }}
    chart: {{ include "controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    addon.open-cluster-management.io/hosted-manifest-location: hosting
stringData:
  hub.group: {{ .Values.hubGroup }}
