# Copyright Contributors to the Open Cluster Management project
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:governance-standalone-hub-templating
rules:
# Rules for maintaining the lease on the hub
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - governance-policy-framework
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
# Base permissions for hub templates, all others must be configured by users
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - get
  - list
  - watch
