# Copyright Contributors to the Open Cluster Management project
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "open-cluster-management:governance-standalone-hub-templating"
  namespace: "{{ .ClusterName }}"
roleRef:
  kind: ClusterRole
  name: open-cluster-management:governance-standalone-hub-templating
  apiGroup: rbac.authorization.k8s.io
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "{{ .Group }}"
